config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: "pages#home"

  resources :tweets, only: :create	
  resources :users, only: [:index, :show]
  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets

  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id", dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
   foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def following?(other_user)
  	#Este método checa se um usuário está seguindo o outro
  	following.include? other_user
  end

  def follow!(other_user)
  	#Este método criará o relacionamento entre um usuário e outro
  	following << other_user
  end

  def unfollow!(other_user)
  	#Este método apagará o relacionamento entre o usuário e outro
  	following.destroy(other_user)
  end

  def feed
  	#Este método irá gerar o feed para o usuário
  	users_ids = following.pluck(:id)
  	users_ids << self.id
  	Tweet.where(user_id: users_ids).order(created_at: :desc)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		if user_signed_in?
			@tweet = current_user.tweets.build
		end	
	end

	def following
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		@user = User.find(params[:id])

		if current_user.following? @user
			redirect_to user_path, alert: 'Usuário já está sendo seguido'
		else
			current_user.follow! @user
			redirect_to user_path(@user), notice: 'Usuário seguido com sucesso'
		end
	end

	def destroy
		@user = User.find(params[:id])

		current_user.unfollow! @user
		redirect_to user_path(@user), notice: 'Usuário deixou de ser seguido'
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	def create
		@tweet = current_user.tweets.new(tweet_params)

		if @tweet.save
			redirect_to root_path, notice: 'Tweet foi salvo'

		else	
			redirect_to root_path, notice: 'Tweet não foi salvo'
		end
	end


	private

	def tweet_params
		params.require(:tweet).permit(:content)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all		
	end

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationship_helper.rb
module RelationshipHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter Bootcamp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<header>
  		<div class="notificacoes">
  			<p class="notice"><%= notice %></p>
        	<p class="alert"><%= alert %></p>
  		</div>
  	</header>

  	<section>
  		<%= yield %>
  	</section>

   <footer>
   	   <p>Feito no bootcamp</p>
   </footer>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Estamos na Home</h1>

	<%if user_signed_in?%>
		Olá, <%= current_user.email %>
		<hr>

		<h2>Lista de Tweets</h2>

		<%= form_for @tweet do |f| %>
			<%= f.text_field :content %>
			<%= f.submit  %>
		<% end %>

		<ul>
			<% current_user.feed.each do |tweet|%>
				<li><%= tweet.content %> - <% tweet.user.email %></li>
			<% end %>
		</ul>	
		<br>
	
		<%= link_to 'Sair', destroy_user_session_path, method: :delete %>
	
	<% else %>
		<%= link_to 'Clique aqui para logar', new_user_session_path %>
	<% end %>

app/views/users/index.html.erb
<h1>Usuários</h1>

<% @users.each do |user| %>
	<%= link_to user.email, user_path(user) %> <br>
<% end %>

app/views/users/show.html.erb
<h1>Perfil do <%= @user.email %></h1>

<h2>Tweets (<%= @user.tweets.count %>)</h2>

<% if current_user.following? @user %>
	<%= link_to 'Unfollow', relationship_path(@user), method: :delete %>
<% else %>
	<%= link_to 'Follow', relationships_path(id: @user.id), method: :post %>
<% end %>

	<% if @user.tweets.empty? %>
		<p>Usuário ainda não tem tweets</p>
	<% else %>
		<ul>
			<% @user.tweets.each do |tweet|%>
				<li><%= tweet.content %></li>
			<% end %>
		</ul>
	<% end %>		